### ISSUE TITLE
Date format in english

### ISSUE THREAD

**Issue by NikoS34** [alexylem/jarvis-time#1]
Sur un Raspbian installé en US le plugin FR est utilisable sauf pour le nom de la semaine (ex.Saturday).
Ça serait bien de prévoir un paramètre de localisation de type LC_TIME dans l'installation ou le configure du plugin ?

ps: merci pour tout le boulot sur Jarvis, c'est un super projet !

**Comment by alexylem** [comment]
Essayes s'il te plait (dans le terminal):

``` shell
$> LC_TIME=fr_FR.UTF-8 date
```

Ca donne quoi?

Il faut avoir les locales FR installées:

``` shell
$> locale -a
C
C.UTF-8
en_GB.utf8
POSIX
```

Si elles ne sont pas dans la liste il faut les installer avec

``` shell
$> sudo dpkg-reconfigure locales
```

**Comment by NikoS34** [comment]
En effet, j'avais bien rajouté les locales en FR
$> locale -a
C
C.UTF-8
en_GB.utf8
fr_FR.utf8
POSIX

par contre pas réussi à changer que le LC_TIME
$> LC_TIME=fr_FR.UTF-8 date
bash: warning: setlocale: LC_TIME: cannot change locale (fr_FR.UTF-8)
dimanche 23 octobre 2016, 12:18:26 (UTC+0200)
$> date
Sun 23 Oct 12:24:07 CEST 2016

Une idée ?

**Comment by alexylem** [comment]
C'est vraiment bizarre sur certaines distributions comme la tienne c'est `utf8` et non pas `UTF-8`.
Essaye donc:

``` shell
$> LC_TIME=fr_FR.utf8 date
```

Plus d'info ici:
http://superuser.com/questions/999133/differences-between-en-us-utf8-and-en-us-utf-8

**Comment by NikoS34** [comment]
idem
$> LC_TIME=fr_FR.utf8 date
bash: warning: setlocale: LC_TIME: cannot change locale (fr_FR.UTF-8)
dimanche 23 octobre 2016, 12:31:07 (UTC+0200)
$> date
Sun 23 Oct 12:32:42 CEST 2016

**Comment by alexylem** [comment]
Pourtant ca marche... (il te mets bien la date en français) je cherche à voir comment se débarrasser du warning...

**Comment by alexylem** [comment]
Ok essaye sans le .utf

```
LC_TIME=fr_FR date
```

**Comment by NikoS34** [comment]
$> LC_TIME=fr_FR date
bash: warning: setlocale: LC_TIME: cannot change locale (fr_FR.UTF-8)
Sun Oct 23 13:54:49 CEST 2016
$> date
Sun 23 Oct 13:55:29 CEST 2016

**Comment by alexylem** [comment]
Bon... à mon avis tu as un pb avec tes locales, rien à voir avec Jarvis mais je vais qd même essayer de t'aider à résoudre ton pb...

``` shell
$> sudo dpkg-reconfigure locales
```

Assures-toi que `fr_FR.UTF-8` est bien sélectionné (quelque-soit la manière dont est écrit  `utf8`). Vérifie les autres, et déselectionne ceux don't tu n'as pas besoin.
Ensuite il va te demande de choisir la langue par défaut de ton système, si tu veux garder l'anglais tu peux.
Ensuite réessayes (avec la bonne écriture de `utf8/UTF-8`), chez moi ca marche:

``` shell
$> locale -a
C
C.UTF-8
en_GB.utf8
fr_FR.utf8
POSIX
$> date
Sun 23 Oct 14:52:44 CEST 2016
$> LC_TIME=fr_FR.UTF-8 date
dimanche 23 octobre 2016, 14:49:54 (UTC+0200)
```

**Comment by NikoS34** [comment]
une solution qui fonctionne:
- créer le fichier locale.conf dans /etc
  avec juste la ligne  LC_TIME=fr_FR.UTF-8
- rebooter le RaspPi et là c'est OK

$> locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

$> date
dimanche 23 octobre 2016, 14:51:15 (UTC+0200)

et là c'est OK pour utiliser jarvis-time en FR sur un OS en GB !

Mais pour intégrer cette possibilité dans la config du plugin il faudrait peut-être mieux une soluce sans reboot...

**Comment by alexylem** [comment]
Non mais la tu as mis fr_FR comme locale **par défaut** pour la date et l'heure...
Alors que justement je modifie le plugin pour que ca soit changé à la volée en fonction de la langue choisie par l'utilisateur.
Exemple, mon système est en anglais par défaut:

``` shell
$> locale | grep LC_TIME
LC_TIME="en_GB.UTF-8"
```

Mais je peux demander la date en Français

``` shell
$> LC_TIME=fr_FR.UTF-8 date
dimanche 23 octobre 2016, 14:49:54 (UTC+0200)
```

C'est ainsi que je vais configurer le plugin Time. Pas besoin de reboot si on ne change pas la langue du système par défaut 😄 
J'espère que ca marchera aussi pour toi.

**Comment by NikoS34** [comment]
OK c'est clair, je vais donc essayer sur une autre distrib (toute neuve)...
@+

ps: j'ai des soucis avec les commandes imbriquées, je vais faire un ticket dans jarvis asap.
