### ISSUE TITLE
plugin non compatible avec le plugin jeedom ou inverse

### ISSUE THREAD

**Issue by dud29** [alexylem/jarvis-time#2]
Bonjour, j'ai installé le plugin Jeedom en premier, j'ai ensuite installé ce plugin. La réponse à toutes mes demandes concernant l'heure ou la date me retourne 'je ne comprend pas' (réponse de Jeedom si il ne trouve pas de correspondance dans ses interactions). Je pense que Jarvis ne devrait envoyer un ordre à Jeedom que si il ne trouve rien d'autre au niveau des commandes du fichier jarvis-commands (je crois que ça c'est déjà le cas) mais aussi dans tous les autres plugins.
dud29.

**Comment by alexylem** [comment]
Incroyable que je n'ai pas pensé à ca...
C'est parce que le plugin Jeedom "capte" toutes les commandes (pattern: `*`) et il est passé en premier par rapport à son nom (Jeedom < Time).
Une solution simple est de changer le pattern à (`*JEEDOM*`) mais il faudra dire: "Jeedom allume la lumière"...

**Comment by alexylem** [comment]
Ceci sera corrigé par:
alexylem/jarvis#220

**Comment by alexylem** [comment]
Corrigé, voir:
alexylem/jarvis#220
