### ISSUE TITLE
Prononciation 9 heures

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis-time#4]
De @Jean-Bernard-Hallez
>Cool.... il y a un petit truc qui tu n'as pas modifié et c'est peut-être volontaire de ta part... j'utilise google pour le speech engine... et quand il prononce tout ce qui tourne autour de 9h00... il prononce "il est neuf FFheure vingt-cinq"... il fait la liaison.. ce qui résonne pas vraiment bien... pour contourner l'obstacle j'ai fait ceci: *QUELLE HEURE*==say "il est $(date +"%$formatheure") h $([ $(date +"%-M") -eq 0 ] || date +"%-M")" et il prononce normalement il est neuf heure vingt-cinq.... il n'y a pas de FFFF en trop lol...

**Comment by alexylem** [comment]
Donc tu veux dire remplacer `heures` par `h`?
Après faudrait tester avec les autres speech engines...

**Comment by Jean-Bernard-Hallez** [comment]
Oui c'est ça @alexylem  mais je n'ai pas testé avec les autres speech engines...

**Comment by alexylem** [comment]
Bon alors en testant avec:
```
$> ./jarvis.sh -s "il est 9 heures"
```
* Google: 👎  ("Il est 9 ffeures")
* Voxygen: 👍 
* SVOX Pico: 👍 
* eSpeak: 👍 
* OSX Say: 👍 

Et en testant avec:
```
$> ./jarvis.sh -s "il est 9 h"
```
* Google: 👍 
* Voxygen: 👍 
* SVOX Pico: 👎  ("Il est 9 hache")
* eSpeak: 👎  ("Il est 9 hache")
* OSX Say: 👍 

Donc avec `heures` tout fonctionne sauf Google. Avec `h` ca casse eSpeak et SVOX Pico (qui est le moteur recommandé). Donc je pense que je ne vais pas changer juste pour corriger un bug de Google. L'idéal serait de contacter google pour leur dire que leur synthèse vocale n'est pas au point 😄 . Je te conseille plutôt d'utiliser Voxygen (aussi en ligne) qui a de très bonne voix féminines et masculines.

**Comment by Jean-Bernard-Hallez** [comment]
Ce que tu peux faire pour la propreté du vocal car il vaut mieux avoir tu top de chez top que du simple top...  c'est tout simplement renvoyer ton  say  vers une function (say==jv_pg_ct_time) qui permet lire ttsengine avec un cat  pour diriget le say en fonction du  Speech synthesis. Et si c'est avec Google de faire avec un h et pour les autres avec heure et tout est nickel...

**Comment by alexylem** [comment]
Dans le cadre de https://github.com/alexylem/jarvis/issues/394, il y aura probablement un hook juste avant de parler. Donc on peut imaginer que ce hook puisse permettre d'altérer le texte avant qu'il soit prononcer et ainsi de faire un:
```shell
$order="${order//heures/h}"
```
T'en penses quoi?

**Comment by Jean-Bernard-Hallez** [comment]
Une idée oui et non...  pourquoi contourner quand on peut aller tout droit... il faut que chaque personne  fasse une modif de son côté selon les situation... ça risque de ne pas être évident à mettre en oeuvre  pour tout le monde...  comme la pour le time ça ne serra pas une mise à jour automatique en fonction de son sst...

**Comment by alexylem** [comment]
Oui en effet tu as raison il y a une solution simple. Allez je la mets en place.
